# Generated by Django 3.2.7 on 2021-11-17 08:15

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=[], primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ips',
            field=models.Field(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='profile',
            name='subprofiles',
            field=models.Field(blank=True, default={}),
        ),
    ]
