# Generated by Django 3.2.7 on 2021-11-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211117_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ips',
            field=models.Field(default=[]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subprofiles',
            field=models.Field(default={}),
        ),
    ]
