# Generated by Django 3.2.7 on 2021-11-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211117_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ips',
            field=models.Field(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subprofiles',
            field=models.Field(blank=True, default={}, null=True),
        ),
    ]
