# Generated by Django 3.2.7 on 2021-11-23 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20211117_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='btc_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='usd_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='usd_balance',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
